language: clojure
jdk:
  - oraclejdk8
lein: lein2
sudo: false
before_script: lein2 clean
script: lein2 test!
cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master
  - mainline
notifications:
  slack:
    secure: Nh9LtRqkzAzH3EjOgrVPirXR6ztD2dOqyB/4TIQkOO2ta5P2Kcn2BMDkNuhqTopVkMummhLz0avLxcXpcsYlFi01PS1j1GwSB82sYFMU1Ob8Zw024JAdIM8y4oVBgP0BuBG6STBjrJTGCHJi+UrwbT6fcPw0a7qbryBnh+/hImk/xDfM3K91RjinlLTVAbEWrcT8zywgBDR0BZIJg5RJsleX7MHCl1v4ckLJslcWPiIN5LAnxGajOBTTTVbpv46XVfOFRI1LJ5zPn48k7T/sPXm88a9UsC1y8wFB7sZkvx2iSC9gMrdx/vuunH/sKyC81xwAcoIP0mNcXbfT2Uny+/tGrn/r0WxqG/UqB8rq+fJB/ksC6esGb/c6zTC6vJlzApVizZnVvNMxxedj4NzT0UOP0DRxEb1tgg/FC3U/XriS6TAtiECIpx7sa33GnY9JwLFz9oNXBrSCyKT/3tF5btjf0LWCIGLH6Pz+z6blcj63G87GBxf+zHPU3CgLAFrHBUPdGtfdCspLzJxdky2TYM4jzWWGR/plKZ3ZwWAz/lIq8sd71AWRYlf/gabzbnQVIj8xpOt0I3EQuYoHpstoXPTOSa66DYoMfolJRn1eRZQgh7Sj6yvtJAAjsPYjkmDPiLuZaXRtQQ/35d1leMs2fdFYA+rK9p7ux+Eh63sCmUg=
